title: Services
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          fields:

            header.services:
              type: list
              autofocus: true
              collapsed: true
              style: vertical
              label: Sections
              fields:
                .title:
                  label: Title
                  type: text
                .content:
                  label: Content
                  type: editor

            content:
              unset@: true

            uploads:
              unset@: true
