version: "3.2"
services:
  web:
    image: spark
    build:
      context: .
      dockerfile: Dev_Dockerfile
    ports:
      - "80:8080"
    volumes:
      - type: bind
        source: ./user
        target: /usr/share/nginx/html/user
