version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: ./Dev_Dockerfile
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
