title: Service
'@extends': default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      default: modular/text
                      '@data-options': '\Grav\Common\Page\Pages::modularTypes'
            overrides:
              fields:
                header.template:
                  default: modular/text
                  '@data-options': '\Grav\Common\Page\Pages::modularTypes'
        content:
          fields:
            header.svgFile:
              type: text
              label: SVG Filename
