@extends:
  '@parent'

form:
  fields:
    contactdetails:
      type: section
      title: Contact Details
      underline: true

      fields:
        contactdetails.name:
          type: text
          label: Name
          size: large

        contactdetails.address:
          type: textarea
          label: Address
          rows: 4

        contactdetails.tel:
          type: text
          label: Telephone
          size: large

        contactdetails.email:
          type: text
          label: E-mail
          size: large
